"""Build scaling_scanner_strategy.pine from scaling_scanner.pine.

The indicator queues order instructions (ordQ). This turns it into a TradingView strategy that
places them, so the Strategy Tester trades exactly the indicator's entries and exits:
TP1 takes a partial (TP1 %), the rest runs to the stop (moved to breakeven) or the structure exit.
Size = the indicator's risk-% tiers, using the strategy's own equity.

Usage: python pine/build_strategy.py
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "scaling_scanner.pine"
OUT = HERE / "scaling_scanner_strategy.pine"

HEADER_OLD = 'indicator("Gold / ES Scaling Scanner", shorttitle = "ScaleScan", overlay = true, max_labels_count = 500, max_boxes_count = 100, max_lines_count = 500)'
HEADER_NEW = ('strategy("Gold / ES Scaling Scanner (Strategy)", shorttitle = "ScaleScan ST", overlay = true, '
              'max_labels_count = 500, max_boxes_count = 100, max_lines_count = 500, initial_capital = 10000, '
              'currency = currency.USD, pyramiding = 20, process_orders_on_close = true, calc_on_every_tick = false)\n\n'
              'grpBT = "Strategy tester"\n'
              'btS    = input.bool(true, "Trade Setup S (swing)", group = grpBT, display = display.none)\n'
              'btA    = input.bool(true, "Trade Setup A (2H)", group = grpBT, display = display.none)\n'
              'btB    = input.bool(true, "Trade Setup B (15m)", group = grpBT, display = display.none)\n'
              'tp1Pct = input.float(50, "Close at TP1 (%)", minval = 1, maxval = 100, group = grpBT, tooltip = "Partial at TP1; the rest runs to the stop (breakeven after +$2) or the structure exit.", display = display.none)')

EXECUTOR = '''    for o in ordQ
        on = (o.setup == "S" and btS) or (o.setup == "A" and btA) or (o.setup == "B" and btB)
        if on
            if o.kind == "entry" and o.qty > 0
                strategy.entry(o.id, o.dir == 1 ? strategy.long : strategy.short, qty = o.qty, limit = o.price)
                if not na(o.tp1)
                    strategy.exit(o.id + " TP1", o.id, qty_percent = tp1Pct, limit = o.tp1, stop = o.stop, comment = o.id + " TP1")
                strategy.exit(o.id + " RUN", o.id, stop = o.stop, comment = o.id + " stop")
            else if o.kind == "be"
                if not na(o.tp1)
                    strategy.exit(o.id + " TP1", o.id, qty_percent = tp1Pct, limit = o.tp1, stop = o.stop, comment = o.id + " TP1")
                strategy.exit(o.id + " RUN", o.id, stop = o.stop, comment = o.id + " BE")
            else if o.kind == "close"
                strategy.close(o.id, comment = o.id + " structure exit")
            else if o.kind == "cancel"
                strategy.cancel(o.id)'''

REPLACEMENTS = [
    (HEADER_OLD, HEADER_NEW),
    ("            eqNow = curEq > 0 ? curEq : startEq + book.pnl", "            eqNow = strategy.equity"),
    ("            growth = (eqNow / startEq - 1) * 100", "            growth = (eqNow / strategy.initial_capital - 1) * 100"),
    ("    // @@STRATEGY_EXECUTOR@@", EXECUTOR),
    ("// Gold / ES Scaling Scanner v", "// Gold / ES Scaling Scanner (STRATEGY build, generated by build_strategy.py) v"),
]


def build() -> str:
    text = SRC.read_text(encoding="utf-8")
    for old, new in REPLACEMENTS:
        if text.count(old) != 1:
            raise SystemExit(f"build_strategy: expected exactly one match for {old[:60]!r}")
        text = text.replace(old, new)
    OUT.write_text(text, encoding="utf-8")
    return text


if __name__ == "__main__":
    t = build()
    print(f"wrote {OUT.name}: {t.count(chr(10))} lines")
